### ISSUE TITLE
memory issues on AWS EC2 instances

### ISSUE THREAD

**Issue by vardhanv** [vardhanv/cosbench_ng#26]
08:28:51.074UTC ERROR a.r.a.ArteryTransport(akka://system) akka.remote.artery.ArteryTransport(akka://system): Inbound message stream failed. Restarting it. Insufficient usable storage for new log of length=50332096 in /dev/shm (shm)
io.aeron.exceptions.RegistrationException: Insufficient usable storage for new log of length=50332096 in /dev/shm (shm)
	at io.aeron.ClientConductor.onError(ClientConductor.java:295)
	at io.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:79)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
	at io.aeron.DriverListenerAdapter.pollMessage(DriverListenerAdapter.java:59)
	at io.aeron.ClientConductor.doWork(ClientConductor.java:432)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:464)
	at io.aeron.ClientConductor.addPublication(ClientConductor.java:187)
	at io.aeron.Aeron.addPublication(Aeron.java:197)
	at akka.remote.artery.AeronSink$$anon$1.<init>(AeronSink.scala:103)
	at akka.remote.artery.AeronSink.createLogicAndMaterializedValue(AeronSink.scala:100)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:627)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:524)
	at akka.remote.artery.Association.akka$remote$artery$Association$$runOutboundOrdinaryMessagesStream(Association.scala:562)
	at akka.remote.artery.Association.runOutboundStreams(Association.scala:502)
	at akka.remote.artery.Association.associate(Association.scala:494)
	at akka.remote.artery.AssociationRegistry.association(Association.scala:756)
	at akka.remote.artery.AssociationRegistry.setUID(Association.scala:771)
	at akka.remote.artery.ArteryTransport.completeHandshake(ArteryTransport.scala:1010)
	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:201)
	at akka.remote.artery.InboundHandshake$$anon$2$$anon$4.onPush(Handshake.scala:192)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:404)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by vardhanv** [comment]
Added aeron flag to startup scripts reduce required memory footprint
