### ISSUE TITLE
aeron log storage issue

### ISSUE THREAD

**Issue by vardhanv** [vardhanv/cosbench_ng#31]
Started: 41 % s3ops22:37:27.309 ERROR a.r.a.ArteryTransport(akka://system) Aeron error: 21 observations from 12/30/2017 22:37:05.769 to 12/30/2017 22:37:24.980 for:
 java.lang.IllegalStateException: Insufficient usable storage for new log of length=25166272 in /dev/shm (shm)
	at io.aeron.driver.buffer.RawLogFactory.newInstance(RawLogFactory.java:148)
	at io.aeron.driver.buffer.RawLogFactory.newNetworkedImage(RawLogFactory.java:109)
	at io.aeron.driver.DriverConductor.newPublicationImageLog(DriverConductor.java:821)
	at io.aeron.driver.DriverConductor.onCreatePublicationImage(DriverConductor.java:200)
	at io.aeron.driver.cmd.CreatePublicationImageCmd.execute(CreatePublicationImageCmd.java:62)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:998)
	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:113)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:147)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:140)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vardhanv** [comment]
i think this is related https://github.com/real-logic/Aeron/issues/329

**Comment by vardhanv** [comment]
For now - increased shared memory size
